spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/azumher?useTimezone=true&serverTimezone=UTC
    username: root
    password: susana
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true            